USE KiKiPups
GO



IF OBJECT_ID('EventAttendant') IS NOT NULL DROP TABLE EventAttendant;
IF OBJECT_ID('EventData') IS NOT NULL DROP TABLE [EventData];
IF OBJECT_ID('Event') IS NOT NULL DROP TABLE [Event];

IF OBJECT_ID('ArticleData') IS NOT NULL DROP TABLE ArticleData;
IF OBJECT_ID('Article') IS NOT NULL DROP TABLE Article;

IF OBJECT_ID('GroupChat') IS NOT NULL DROP TABLE GroupChat;
IF OBJECT_ID('Chat') IS NOT NULL DROP TABLE Chat;

IF OBJECT_ID('UserFormEntry') IS NOT NULL DROP TABLE UserFormEntry;
IF OBJECT_ID('UserForm') IS NOT NULL DROP TABLE UserForm;

IF OBJECT_ID('RulevalueData') IS NOT NULL DROP TABLE RulevalueData;
IF OBJECT_ID('RuleValue') IS NOT NULL DROP TABLE RuleValue;
IF OBJECT_ID('Rule') IS NOT NULL DROP TABLE [Rule];

IF OBJECT_ID('FormFieldValue') IS NOT NULL DROP TABLE FormFieldValue;
IF OBJECT_ID('FormFieldData') IS NOT NULL DROP TABLE FormFieldData;
IF OBJECT_ID('FormField') IS NOT NULL DROP TABLE FormField;
IF OBJECT_ID('Form') IS NOT NULL DROP TABLE Form;

IF OBJECT_ID('UserGroupRelation') IS NOT NULL DROP TABLE UserGroupRelation;
IF OBJECT_ID('GroupPost') IS NOT NULL DROP TABLE GroupPost;
IF OBJECT_ID('GroupMember') IS NOT NULL DROP TABLE GroupMember;
IF OBJECT_ID('GroupData') IS NOT NULL DROP TABLE GroupData;
IF OBJECT_ID('Group') IS NOT NULL DROP TABLE [Group];

IF OBJECT_ID('PostData') IS NOT NULL DROP TABLE PostData;
IF OBJECT_ID('PostReaction') IS NOT NULL DROP TABLE PostReaction;
IF OBJECT_ID('Post') IS NOT NULL DROP TABLE Post;

IF OBJECT_ID('UserRelation') IS NOT NULL DROP TABLE UserRelation;
IF OBJECT_ID('UserData') IS NOT NULL DROP TABLE UserData;
IF OBJECT_ID('User') IS NOT NULL DROP TABLE [User];

IF OBJECT_ID('StructureData') IS NOT NULL DROP TABLE StructureData;
IF OBJECT_ID('Structure') IS NOT NULL DROP TABLE Structure;
IF OBJECT_ID('Data') IS NOT NULL DROP TABLE Data;
IF OBJECT_ID('Dictionary') IS NOT NULL DROP TABLE Dictionary;
GO



CREATE TABLE Dictionary (
	DictionaryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	Name VARCHAR(255) NOT NULL,
	Label VARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[Version] REAL NULL,

	ParentDictionaryID INT NULL FOREIGN KEY REFERENCES Dictionary (DictionaryID),
	Ordinality INT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE Data (
	DataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DictionaryID INT NULL FOREIGN KEY REFERENCES Dictionary (DictionaryID),

	Name VARCHAR(255) NOT NULL,
	Label VARCHAR(255) NOT NULL,
	Value NVARCHAR(MAX) NOT NULL,
	DDataTypeID INT NULL FOREIGN KEY REFERENCES Data (DataID),

	ParentDataID INT NULL FOREIGN KEY REFERENCES Data (DataID),
	Ordinality INT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE [User] (
	UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DUserTypeID INT NULL FOREIGN KEY REFERENCES Data (DataID),

	Username VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	[Password] VARCHAR(255) NOT NULL,
	Salt VARCHAR(255) NOT NULL,
	
	LastLoginDateTimeUTC DATETIME2(3) NULL,
	LastLoginIP VARCHAR(255) NULL,

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE UserData (
	UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NOT NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE UserRelation (
	UserRelationID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	FromUserID INT NULL FOREIGN KEY REFERENCES [User] (UserID),
	ToUserID INT NULL FOREIGN KEY REFERENCES [User] (UserID),
	DRelationTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE Post (
	PostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	DPostTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DContentTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Content NVARCHAR(MAX) NOT NULL,
	
	ParentPostID INT NULL FOREIGN KEY REFERENCES Post (PostID),
	Ordinality INT NULL,
	
	CreatedByUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE PostReaction (
	PostReactionID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	PostID INT NULL FOREIGN KEY REFERENCES Post (PostID),
	Value NVARCHAR(255) NOT NULL,
	
	CreatedByUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PostData (
	PostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	DPostDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NOT NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE [Group] (
	GroupID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DGroupTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	Name VARCHAR(255) NULL,
	[Description] NVARCHAR(MAX) NULL,
	
	ParentGroupID INT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	Ordinality INT NULL,

	CreatedByUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE GroupMember (
	GroupMemberID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	GroupID INT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	UserID INT NULL FOREIGN KEY REFERENCES [User] (UserID),
	DMembershipTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE GroupPost (
	GroupPostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	GroupID INT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	PostID INT NULL FOREIGN KEY REFERENCES Post (PostID),
	DGroupPostTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	ParentGroupID INT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	Ordinality INT NULL,

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE GroupData (
	GroupID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	DGroupDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NOT NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE UserGroupRelation (
	UserGroupRelationID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	FromUserID INT NULL FOREIGN KEY REFERENCES [User] (UserID),
	ToGroupID INT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	DRelationTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE Form (
	FormID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	Name VARCHAR(255) NULL,
	Label VARCHAR(255) NULL,
	[Description] NVARCHAR(MAX) NULL,
	DFormTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE FormField (
	FormFieldID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	FormID INT NOT NULL FOREIGN KEY REFERENCES Form (FormID),
	DFormFieldTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DDictionaryID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	Name VARCHAR(255) NOT NULL,
	Label VARCHAR(255) NULL,

	ParentFormFieldID INT NOT NULL FOREIGN KEY REFERENCES FormField (FormFieldID),
	Ordinality INT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE FormFieldValue (
	FormFieldValueID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	FormFieldID INT NOT NULL FOREIGN KEY REFERENCES FormField (FormFieldID),
	Value NVARCHAR(MAX) NULL,
	Ordinality INT NULL
);

CREATE TABLE FormFieldData (
	FormFieldDataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	FormFieldID INT NOT NULL FOREIGN KEY REFERENCES FormField (FormFieldID),
	DFormFieldDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NULL
);


CREATE TABLE [Rule] (
	RuleID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	FormID INT NOT NULL FOREIGN KEY REFERENCES Form (FormID),
	Name VARCHAR(255) NULL,
	DComparatorTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DRuleResultTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE RuleValue (
	RuleValueID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	FormFieldID INT NOT NULL FOREIGN KEY REFERENCES FormField (FormFieldID),
	DRuleValueTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),			-- ComparatorLeft, ComparatorRight, RuleResult, etc.
	Value NVARCHAR(MAX) NULL,
	Ordinality INT NULL
);

CREATE TABLE RuleValueData (
	RuleValueDataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	RuleValueID INT NOT NULL FOREIGN KEY REFERENCES RuleValue (RuleValueID),
	DRuleValueDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NULL
);



CREATE TABLE UserForm (
	UserFormID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	FormID INT NOT NULL FOREIGN KEY REFERENCES Form (FormID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE UserFormEntry (
	UserFormEntryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	UserFormID INT NOT NULL FOREIGN KEY REFERENCES UserForm (UserFormID),
	FormFieldID INT NOT NULL FOREIGN KEY REFERENCES FormField (FormFieldID),
	Value NVARCHAR(MAX) NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE Structure (
	StructureID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	Name VARCHAR(255) NULL,
	Label VARCHAR(255) NULL,
	[Description] NVARCHAR(MAX) NULL,
	DStructureTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE StructureData (
	StructureDataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	StructureID INT NOT NULL FOREIGN KEY REFERENCES Structure (StructureID),
	DataID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DStructureDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	ParentStructureDataID INT NOT NULL FOREIGN KEY REFERENCES StructureData (StructureDataID),
	Ordinality INT NULL
);



CREATE TABLE Chat (
	ChatID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	SenderUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	ReceiverUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	PostID INT NOT NULL FOREIGN KEY REFERENCES [Post] (PostID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE GroupChat (
	GroupChatID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	SenderUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	ReceiverGroupID INT NOT NULL FOREIGN KEY REFERENCES [Group] (GroupID),
	PostID INT NOT NULL FOREIGN KEY REFERENCES [Post] (PostID),
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE Article (
	ArticleID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		
	DArticleTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),	
	DArticleCategoryID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),

	Name VARCHAR(255) NOT NULL,
	CreatorUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	PostID INT NOT NULL FOREIGN KEY REFERENCES Post (PostID),
	Tags VARCHAR(255) NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE ArticleData (
	ArticleDataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	ArticleID INT NOT NULL FOREIGN KEY REFERENCES Article (ArticleID),
	DArticleDataID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NULL
);



CREATE TABLE [Event] (
	EventID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		
	DEventTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),	
	DEventCategoryID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	
	Name VARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	Location NVARCHAR(MAX) NULL,
	StartDateTimeUTC DATETIME2(3) NULL,
	EndDateTimeUTC DATETIME2(3) NULL,
	DTimeZoneOffsetID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),

	CreatorUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	PostID INT NOT NULL FOREIGN KEY REFERENCES Post (PostID),
	Tags VARCHAR(255) NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
);

CREATE TABLE [EventData] (
	EventDataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	EventID INT NOT NULL FOREIGN KEY REFERENCES [Event] (EventID),
	DEventDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NULL
);

CREATE TABLE EventAttendant (
	EventAttendantID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	EventID INT NOT NULL FOREIGN KEY REFERENCES [Event] (EventID),
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	DEventAttendantTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID)
);