USE KiKiPups
GO



IF OBJECT_ID('PostData') IS NOT NULL DROP TABLE PostData;
IF OBJECT_ID('PostReaction') IS NOT NULL DROP TABLE PostReaction;
IF OBJECT_ID('Post') IS NOT NULL DROP TABLE Post;

IF OBJECT_ID('UserData') IS NOT NULL DROP TABLE UserData;
IF OBJECT_ID('User') IS NOT NULL DROP TABLE [User];

IF OBJECT_ID('Data') IS NOT NULL DROP TABLE Data;
IF OBJECT_ID('Dictionary') IS NOT NULL DROP TABLE Dictionary;




CREATE TABLE Dictionary (
	DictionaryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	Name VARCHAR(255) NOT NULL,
	Label VARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[Version] REAL NULL,

	ParentDictionaryID INT NULL FOREIGN KEY REFERENCES Dictionary (DictionaryID),
	Ordintality INT NULL
);

CREATE TABLE Data (
	DataID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DictionaryID INT NULL FOREIGN KEY REFERENCES Dictionary (DictionaryID),

	Name VARCHAR(255) NOT NULL,
	Label VARCHAR(255) NOT NULL,
	Value NVARCHAR(MAX) NOT NULL,
	DDataTypeID INT NULL FOREIGN KEY REFERENCES Data (DataID),

	ParentDataID INT NULL FOREIGN KEY REFERENCES Data (DataID),
	Ordintality INT NULL
);

CREATE TABLE [User] (
	UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DUserTypeID INT NULL FOREIGN KEY REFERENCES Data (DataID),

	Username VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	[Password] VARCHAR(255) NOT NULL,
	Salt VARCHAR(255) NOT NULL,
	
	LastLoginDateTimeUTC DATETIME2(3) NULL,
	LastLoginIP VARCHAR(255) NULL,

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);

CREATE TABLE UserData (
	UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NOT NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);



CREATE TABLE Post (
	PostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	DPostTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	DContentTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Content NVARCHAR(MAX) NOT NULL,
	
	ParentPostID INT NULL FOREIGN KEY REFERENCES Post (PostID),
	Ordinality INT NULL,
	
	CreatedByUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PostReaction (
	PostReactionID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	PostID INT NULL FOREIGN KEY REFERENCES Post (PostID),
	Value NVARCHAR(255) NOT NULL,
	
	CreatedByUserID INT NOT NULL FOREIGN KEY REFERENCES [User] (UserID),
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PostData (
	PostID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	DPostDataTypeID INT NOT NULL FOREIGN KEY REFERENCES Data (DataID),
	Value NVARCHAR(MAX) NOT NULL,
	
	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);